[package]
name = "vibe-survival-game"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = "*"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
noise = "0.8" 