use crate::items::{ItemDefinition, ItemCategory, EquipmentSlot};

pub fn get_initial_item_definitions() -> Vec<ItemDefinition> {
    let initial_items = vec![
        ItemDefinition {
            id: 0,
            name: "Wood".to_string(),
            description: "A sturdy piece of wood.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "wood.png".to_string(),
            damage: None,
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot: None,
        },
        ItemDefinition {
            id: 0,
            name: "Stone".to_string(),
            description: "A chunk of rock.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "stone.png".to_string(),
            damage: None,
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot: None,
        },
        ItemDefinition {
            id: 0,
            name: "Stone Hatchet".to_string(),
            description: "A simple hatchet for chopping wood.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "wood_hatchet.png".to_string(),
            damage: Some(5),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: None,
        },
        ItemDefinition {
            id: 0,
            name: "Stone Pickaxe".to_string(),
            description: "A simple pickaxe for breaking rocks.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "pick_axe.png".to_string(),
            damage: Some(5),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: None,
        },
        ItemDefinition {
            id: 0,
            name: "Rock".to_string(),
            description: "A basic tool for gathering.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "rock_item.png".to_string(),
            damage: Some(1),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: None,
        },
        ItemDefinition {
            id: 0,
            name: "Camp Fire".to_string(),
            description: "Provides warmth and light. Requires fuel.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "campfire.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: false,
            equipment_slot: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Shirt".to_string(),
            description: "Simple protection for the torso.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_shirt.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: Some(EquipmentSlot::Chest),
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Pants".to_string(),
            description: "Simple protection for the legs.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_pants.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: Some(EquipmentSlot::Legs),
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Hood".to_string(),
            description: "Basic head covering.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_hood.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: Some(EquipmentSlot::Head),
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Boots".to_string(),
            description: "Simple footwear.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_boots.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: Some(EquipmentSlot::Feet),
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Gloves".to_string(),
            description: "Basic hand coverings.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_gloves.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: Some(EquipmentSlot::Hands),
        },
        ItemDefinition {
            id: 0,
            name: "Burlap Backpack".to_string(),
            description: "A rough sack for carrying things.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "burlap_backpack.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: Some(EquipmentSlot::Back),
        },
        ItemDefinition {
            id: 0,
            name: "Mushroom".to_string(),
            description: "A common edible fungus.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "mushroom.png".to_string(),
            damage: None,
            is_stackable: true,
            stack_size: 50,
            is_equippable: false,
            equipment_slot: None,
        },
        // --- NEW Item: Wooden Storage Box ---
        ItemDefinition {
            id: 0, // Auto-incremented by SpacetimeDB
            name: "Wooden Storage Box".to_string(),
            description: "A simple container for storing items.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "wooden_storage_box.png".to_string(), // Assume this asset exists client-side
            damage: None,
            is_stackable: false, // Placeables are usually not stackable in inventory
            stack_size: 1,
            is_equippable: false,
            equipment_slot: None,
        },
        ItemDefinition {
            id: 0,
            name: "Hammer".to_string(),
            description: "A heavy hammer that deals high damage but is slow to swing.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "hammer.png".to_string(),
            damage: Some(15),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: None,
        },
        ItemDefinition {
            id: 0,
            name: "Dagger".to_string(),
            description: "A quick dagger that attacks rapidly but deals less damage.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "dagger.png".to_string(),
            damage: Some(5),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: None,
        },
        ItemDefinition {
            id: 0,
            name: "Sword".to_string(),
            description: "A balanced sword with good damage and attack speed.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "sword.png".to_string(),
            damage: Some(10),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot: None,
        },
    ];
    initial_items
}

// --- Weapon Definitions ---
pub const HAMMER_DEF: ItemDefinition = ItemDefinition {
    id: 100,
    name: "Hammer",
    description: "A heavy hammer that deals high damage but is slow to swing.",
    category: ItemCategory::Tool,
    is_equippable: true,
    equipment_slot: None,
    damage: Some(15),
    swing_cooldown_ms: Some(1000),
    durability: Some(100),
    stack_size: 1,
    icon_path: "items/hammer.png",
};

pub const DAGGER_DEF: ItemDefinition = ItemDefinition {
    id: 101,
    name: "Dagger",
    description: "A quick dagger that attacks rapidly but deals less damage.",
    category: ItemCategory::Tool,
    is_equippable: true,
    equipment_slot: None,
    damage: Some(5),
    swing_cooldown_ms: Some(300),
    durability: Some(100),
    stack_size: 1,
    icon_path: "items/dagger.png",
};

pub const SWORD_DEF: ItemDefinition = ItemDefinition {
    id: 102,
    name: "Sword",
    description: "A balanced sword with good damage and attack speed.",
    category: ItemCategory::Tool,
    is_equippable: true,
    equipment_slot: None,
    damage: Some(10),
    swing_cooldown_ms: Some(500),
    durability: Some(100),
    stack_size: 1,
    icon_path: "items/sword.png",
};

// Add to ITEM_DEFINITIONS array
pub const ITEM_DEFINITIONS: &[ItemDefinition] = &[
    // ... existing items ...
    HAMMER_DEF,
    DAGGER_DEF,
    SWORD_DEF,
    // ... rest of existing items ...
];
